In [1]:
from sklearn.preprocessing import LabelBinarizer
import pandas as pd
import numpy as np

In [2]:
num_bin = LabelBinarizer()
num_bin.fit(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'])

LabelBinarizer()

In [3]:
num_bin.classes_

array(['1', '10', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U2')

In [4]:
num_bin.transform(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'])

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0]])

In [5]:
num_bin.transform(['7', '8', '9', '10'])

array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
temp_bin = LabelBinarizer(
    neg_label=-1,
    pos_label=1,
    sparse_output=False
)
temp_bin.fit(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'])
temp_bin.transform(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'])

array([[ 1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1,  1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1,  1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1,  1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1,  1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1,  1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1,  1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1,  1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1,  1],
       [-1,  1, -1, -1, -1, -1, -1, -1, -1, -1]])

In [7]:
num_bin = LabelBinarizer()
num_bin.fit(['Yes', 'No'])
num_bin.transform(['Yes', 'No', 'No', 'Yes', 'Yes', 'No'])

array([[1],
       [0],
       [0],
       [1],
       [1],
       [0]])

In [8]:
from sklearn.preprocessing import MultiLabelBinarizer

In [9]:
multi_bin = MultiLabelBinarizer()

In [10]:
courses = [
    ('Math', 'Physics'),
    ('Math', 'English'),
    ('Math', 'Chemistry'),
    ('Physics', 'Chemistry')
]

In [11]:
multi_bin.fit(courses)
multi_bin.classes_

array(['Chemistry', 'English', 'Math', 'Physics'], dtype=object)

In [12]:
multi_bin.transform(courses)

array([[0, 0, 1, 1],
       [0, 1, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 0, 1]])

In [13]:
new_courses = [
    ('Math', 'Physics'),
    ('Math', 'English', 'Chemistry')
]
multi_bin.transform(new_courses)

array([[0, 0, 1, 1],
       [1, 1, 1, 0]])

In [14]:
from patsy.contrasts import Treatment # Dummy coding

In [15]:
levels = [0, 1, 2]
contrast_without_intercept_0 = Treatment(reference=0).code_without_intercept(levels)
print(contrast_without_intercept_0.matrix)

[[0. 0.]
 [1. 0.]
 [0. 1.]]


In [16]:
contrast_without_intercept_1 = Treatment(reference=1).code_without_intercept(levels)
print(contrast_without_intercept_1.matrix)

[[1. 0.]
 [0. 0.]
 [0. 1.]]


In [17]:
contrast_with_intercept = Treatment(reference=0).code_with_intercept(levels)
print(contrast_with_intercept.matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Contrast Coding

In [18]:
# Simple Effect Contrast Coding
iris = pd.read_csv('data/iris.csv')
iris.sample(10)

Species  sepal_length  sepal_width  petal_length  petal_width
41       Iris-setosa           4.5          2.3           1.3          0.3
124   Iris-virginica           6.7          3.3           5.7          2.1
54   Iris-versicolor           6.5          2.8           4.6          1.5
17       Iris-setosa           5.1          3.5           1.4          0.3
108   Iris-virginica           6.7          2.5           5.8          1.8
116   Iris-virginica           6.5          3.0           5.5          1.8
43       Iris-setosa           5.0          3.5           1.6          0.6
82   Iris-versicolor           5.8          2.7           3.9          1.2
134   Iris-virginica           6.1          2.6           5.6          1.4
19       Iris-setosa           5.1          3.8           1.5          0.3

In [19]:
iris = iris[['Species', 'petal_length']]
iris.sample(10)

Species  petal_length
86   Iris-versicolor           4.7
45       Iris-setosa           1.4
42       Iris-setosa           1.3
110   Iris-virginica           5.1
135   Iris-virginica           6.1
29       Iris-setosa           1.6
101   Iris-virginica           5.1
91   Iris-versicolor           4.6
28       Iris-setosa           1.4
115   Iris-virginica           5.3

In [20]:
iris_species_mean = iris.groupby('Species').mean()
iris_species_mean

petal_length
Species                      
Iris-setosa             1.464
Iris-versicolor         4.260
Iris-virginica          5.552

In [21]:
d1 = iris_species_mean.loc['Iris-versicolor']['petal_length'] - \
    iris_species_mean.loc['Iris-setosa']['petal_length']
d2 = iris_species_mean.loc['Iris-virginica']['petal_length'] - \
    iris_species_mean.loc['Iris-setosa']['petal_length']
d1, d2

(2.796, 4.088000000000001)

In [22]:
from patsy.contrasts import ContrastMatrix

def _name_levels(prefix, levels):
    return [prefix + str(i) for i in levels]

In [23]:
# Code for Simple Effect Contrast Coding
# https://www.statsmodels.org/dev/contrasts.html#user-defined

class SimpleEffect(object):

    def _simple_contrast(self, levels):
        nlevels = len(levels)

        contr = -1./nlevels * np.ones((nlevels, nlevels-1))
        contr[1:][np.diag_indices(nlevels-1)] = (nlevels-1.)/nlevels
    
        return contr
    

    def code_with_intercept(self, levels):
        contrast = np.column_stack((np.ones(len(levels)),
                                        self._simple_contrast(levels)))

        return ContrastMatrix(contrast, _name_levels("Simp.", levels))


    def code_without_intercept(self, levels):
        contrast = self._simple_contrast(levels)

        return ContrastMatrix(contrast, _name_levels("Simp.", levels[:-1]))

In [24]:
import statsmodels.api as sm
import statsmodels.formula.api as smf
mod = smf.ols("petal_length ~ Species", data=iris) # Dummy coding
res = mod.fit()
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:           petal_length   R-squared:                       0.941
Model:                            OLS   Adj. R-squared:                  0.941
Method:                 Least Squares   F-statistic:                     1179.
Date:                Sat, 01 Jan 2022   Prob (F-statistic):           3.05e-91
Time:                        11:26:35   Log-Likelihood:                -84.840
No. Observations:                 150   AIC:                             175.7
Df Residuals:                     147   BIC:                             184.7
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================================
                                 coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------
Intercept                      1.4640      0.061     24.057      0.000       1.344       1.584
Species[T.Iris-versicolor]     2.7960      0.086     32.488      0.000       2.626       2.966
Species[T.Iris-virginica]      4.0880      0.086     47.500      0.000       3.918       4.258
==============================================================================
Omnibus:                        4.393   Durbin-Watson:                   2.000
Prob(Omnibus):                  0.111   Jarque-Bera (JB):                5.370
Skew:                           0.121   Prob(JB):                       0.0682
Kurtosis:                       3.895   Cond. No.                         3.73
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [25]:
# Linear Regression with Simple Effect Contrast Coding

mod = smf.ols("petal_length ~ C(Species, SimpleEffect)", data=iris)
res = mod.fit()
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:           petal_length   R-squared:                       0.941
Model:                            OLS   Adj. R-squared:                  0.941
Method:                 Least Squares   F-statistic:                     1179.
Date:                Sat, 01 Jan 2022   Prob (F-statistic):           3.05e-91
Time:                        11:26:35   Log-Likelihood:                -84.840
No. Observations:                 150   AIC:                             175.7
Df Residuals:                     147   BIC:                             184.7
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
================================================================================================================
                                                   coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------------
Intercept                                        3.7587      0.035    106.978      0.000       3.689       3.828
C(Species, SimpleEffect)Simp.Iris-setosa         2.7960      0.086     32.488      0.000       2.626       2.966
C(Species, SimpleEffect)Simp.Iris-versicolor     4.0880      0.086     47.500      0.000       3.918       4.258
==============================================================================
Omnibus:                        4.393   Durbin-Watson:                   2.000
Prob(Omnibus):                  0.111   Jarque-Bera (JB):                5.370
Skew:                           0.121   Prob(JB):                       0.0682
Kurtosis:                       3.895   Cond. No.                         3.00
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [26]:
levels = [0, 1, 2]
contrast_with_intercept = SimpleEffect().code_with_intercept(levels)
contrast_with_intercept.matrix

array([[ 1.        , -0.33333333, -0.33333333],
       [ 1.        ,  0.66666667, -0.33333333],
       [ 1.        , -0.33333333,  0.66666667]])

In [27]:
contrast_without_intercept = SimpleEffect().code_without_intercept(levels)
contrast_without_intercept.matrix

array([[-0.33333333, -0.33333333],
       [ 0.66666667, -0.33333333],
       [-0.33333333,  0.66666667]])

In [28]:
from sklearn import preprocessing
label_enc = preprocessing.LabelEncoder()

iris_enc = iris.copy()

iris_enc['species_enc'] = label_enc.fit_transform(iris['Species'])

In [29]:
label_enc.classes_

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [30]:
iris_contrast_setosa = contrast_without_intercept.matrix[iris_enc.species_enc - 0, :] # 0 reference level
iris_contrast_setosa[:5]

array([[-0.33333333, -0.33333333],
       [-0.33333333, -0.33333333],
       [-0.33333333, -0.33333333],
       [-0.33333333, -0.33333333],
       [-0.33333333, -0.33333333]])

In [31]:
iris_contrast_versicolor = contrast_without_intercept.matrix[iris_enc.species_enc - 1, :] # 1 reference level
iris_contrast_versicolor[:5]

array([[-0.33333333,  0.66666667],
       [-0.33333333,  0.66666667],
       [-0.33333333,  0.66666667],
       [-0.33333333,  0.66666667],
       [-0.33333333,  0.66666667]])

In [32]:
iris_contrast = pd.DataFrame(iris_contrast_setosa, columns=label_enc.classes_[1:])
iris_contrast.sample(10)

Iris-versicolor  Iris-virginica
110        -0.333333        0.666667
94          0.666667       -0.333333
80          0.666667       -0.333333
16         -0.333333       -0.333333
40         -0.333333       -0.333333
45         -0.333333       -0.333333
28         -0.333333       -0.333333
59          0.666667       -0.333333
84          0.666667       -0.333333
134        -0.333333        0.666667

In [33]:
iris_enc = pd.concat([iris, iris_contrast], axis=1)
iris_enc.sample(10)

Species  petal_length  Iris-versicolor  Iris-virginica
78   Iris-versicolor           4.5         0.666667       -0.333333
55   Iris-versicolor           4.5         0.666667       -0.333333
95   Iris-versicolor           4.2         0.666667       -0.333333
149   Iris-virginica           5.1        -0.333333        0.666667
28       Iris-setosa           1.4        -0.333333       -0.333333
135   Iris-virginica           6.1        -0.333333        0.666667
138   Iris-virginica           4.8        -0.333333        0.666667
49       Iris-setosa           1.4        -0.333333       -0.333333
64   Iris-versicolor           3.6         0.666667       -0.333333
23       Iris-setosa           1.7        -0.333333       -0.333333

In [34]:
X = iris_enc.drop(['Species', 'petal_length'], axis=1)
y = iris_enc['petal_length']

In [35]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X, y)
print(f'Score: {lr.score(X, y)}')

Score: 0.9413189735606261


In [36]:
# Backward Difference Contrast Coding
import category_encoders as ce

In [37]:
iris.groupby('Species').mean().diff()

petal_length
Species                      
Iris-setosa               NaN
Iris-versicolor         2.796
Iris-virginica          1.292

In [39]:
mod = smf.ols("petal_length ~ C(Species, Diff)", data=iris) # Backward Difference
res = mod.fit()
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:           petal_length   R-squared:                       0.941
Model:                            OLS   Adj. R-squared:                  0.941
Method:                 Least Squares   F-statistic:                     1179.
Date:                Sat, 01 Jan 2022   Prob (F-statistic):           3.05e-91
Time:                        11:30:30   Log-Likelihood:                -84.840
No. Observations:                 150   AIC:                             175.7
Df Residuals:                     147   BIC:                             184.7
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
=======================================================================================================
                                          coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------
Intercept                               3.7587      0.035    106.978      0.000       3.689       3.828
C(Species, Diff)[D.Iris-setosa]         2.7960      0.086     32.488      0.000       2.626       2.966
C(Species, Diff)[D.Iris-versicolor]     1.2920      0.086     15.012      0.000       1.122       1.462
==============================================================================
Omnibus:                        4.393   Durbin-Watson:                   2.000
Prob(Omnibus):                  0.111   Jarque-Bera (JB):                5.370
Skew:                           0.121   Prob(JB):                       0.0682
Kurtosis:                       3.895   Cond. No.                         3.00
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [40]:
bd_enc = ce.BackwardDifferenceEncoder(cols=['Species'])
bd_enc

BackwardDifferenceEncoder(cols=['Species'])

In [41]:
species_enc = bd_enc.fit_transform(iris)
species_enc.head()

intercept  Species_0  Species_1  petal_length
0          1  -0.666667  -0.333333           1.4
1          1  -0.666667  -0.333333           1.4
2          1  -0.666667  -0.333333           1.3
3          1  -0.666667  -0.333333           1.5
4          1  -0.666667  -0.333333           1.4

In [42]:
encoded_iris = pd.concat([iris['Species'], species_enc], axis=1)
encoded_iris.sample(10)

Species  intercept  Species_0  Species_1  petal_length
66   Iris-versicolor          1   0.333333  -0.333333           4.5
142   Iris-virginica          1   0.333333   0.666667           5.1
24       Iris-setosa          1  -0.666667  -0.333333           1.9
88   Iris-versicolor          1   0.333333  -0.333333           4.1
95   Iris-versicolor          1   0.333333  -0.333333           4.2
75   Iris-versicolor          1   0.333333  -0.333333           4.4
6        Iris-setosa          1  -0.666667  -0.333333           1.4
20       Iris-setosa          1  -0.666667  -0.333333           1.7
10       Iris-setosa          1  -0.666667  -0.333333           1.5
122   Iris-virginica          1   0.333333   0.666667           6.7

In [43]:
X = encoded_iris.drop(['Species', 'petal_length'], axis=1)
y = encoded_iris['petal_length']

In [44]:
lr = LinearRegression(fit_intercept=False) # Intercept is included as a feature in X
lr.fit(X, y)
print(f'Score: {lr.score(X, y)}')

Score: 0.9413189735606261


In [45]:
# Backward Helmert Contrast Coding (Reverse Helmert)

cars = pd.read_csv('data/auto-mpg.csv', na_values='?')
cars.sample(10)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
33   19.0          6         232.0       100.0    2634          13.0   
258  20.6          6         231.0       105.0    3380          15.8   
58   25.0          4          97.5        80.0    2126          17.0   
149  24.0          4         120.0        97.0    2489          15.0   
73   13.0          8         307.0       130.0    4098          14.0   
175  29.0          4          90.0        70.0    1937          14.0   
232  16.0          8         351.0       149.0    4335          14.5   
371  29.0          4         135.0        84.0    2525          16.0   
176  19.0          6         232.0        90.0    3211          17.0   
231  15.5          8         400.0       190.0    4325          12.2   

     model year  origin                          car name  
33           71       1                       amc gremlin  
258          78       1             buick century special  
58           72       1                dodge colt hardtop  
149          74       3                       honda civic  
73           72       1  chevrolet chevelle concours (sw)  
175          75       2                 volkswagen rabbit  
232          77       1                  ford thunderbird  
371          82       1                    dodge aries se  
176          75       1                         amc pacer  
231          77       1                  chrysler cordoba

In [46]:
cars = cars[['mpg', 'cylinders']]

In [47]:
cars.dropna(inplace=True)

In [48]:
cars.shape

(398, 2)

In [49]:
cars.cylinders.unique()

array([8, 4, 6, 3, 5], dtype=int64)

In [50]:
cars.sort_values(by='cylinders', inplace=True)
cars.reset_index(drop=True, inplace=True)
cars.head(10)

mpg  cylinders
0  18.0          3
1  19.0          3
2  23.7          3
3  21.5          3
4  27.5          4
5  30.0          4
6  25.1          4
7  36.1          4
8  39.4          4
9  36.1          4

In [51]:
cars.mean()

mpg          23.514573
cylinders     5.454774
dtype: float64

In [52]:
cars_grouped = cars.groupby('cylinders').mean()
cars_grouped

mpg
cylinders           
3          20.550000
4          29.286765
5          27.366667
6          19.985714
8          14.963107

In [53]:
cars_grouped.mean() # Mean of all group means. Not same as cars.mpg.mean()

mpg    22.43045
dtype: float64

In [56]:
coeff_cylinder_4 = (cars_grouped.loc[4, 'mpg'] - cars_grouped.loc[3, 'mpg']) / 2
print(f'Coefficient Cylinder 4: {coeff_cylinder_4}')
mean_34 = (cars_grouped.loc[3, 'mpg'] + cars_grouped.loc[4, 'mpg']) / 2
coeff_cylinder_5 = (cars_grouped.loc[5, 'mpg'] - mean_34) / 3
print(f'Coefficient Cylinder 5: {coeff_cylinder_5}')
mean_345 = (cars_grouped.loc[3, 'mpg'] + cars_grouped.loc[4, 'mpg'] + cars_grouped.loc[5, 'mpg']) / 3
coeff_cylinder_6 = (cars_grouped.loc[6, 'mpg'] - mean_345) / 4
print(f'Coefficient Cylinder 6: {coeff_cylinder_6}')
mean_3456 = (cars_grouped.loc[3, 'mpg'] + cars_grouped.loc[4, 'mpg'] + cars_grouped.loc[5, 'mpg'] + cars_grouped.loc[6, 'mpg']) / 4
coeff_cylinder_8 = (cars_grouped.loc[8, 'mpg'] - mean_3456) / 5
print(f'Coefficient Cylinder 8: {coeff_cylinder_8}')

Coefficient Cylinder 4: 4.368382352941175
Coefficient Cylinder 5: 0.8160947712418292
Coefficient Cylinder 6: -1.4371907096171803
Coefficient Cylinder 8: -1.8668359236898637


In [55]:
mod = smf.ols("mpg ~ C(cylinders, Helmert)", data=cars)
res = mod.fit()
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.637
Model:                            OLS   Adj. R-squared:                  0.634
Method:                 Least Squares   F-statistic:                     172.6
Date:                Sat, 01 Jan 2022   Prob (F-statistic):           3.68e-85
Time:                        11:44:21   Log-Likelihood:                -1180.8
No. Observations:                 398   AIC:                             2372.
Df Residuals:                     393   BIC:                             2392.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================================
                                 coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------
Intercept                     22.4305      0.739     30.353      0.000      20.978      23.883
C(cylinders, Helmert)[H.4]     4.3684      1.194      3.657      0.000       2.020       6.717
C(cylinders, Helmert)[H.5]     0.8161      0.994      0.821      0.412      -1.138       2.770
C(cylinders, Helmert)[H.6]    -1.4372      0.329     -4.371      0.000      -2.084      -0.791
C(cylinders, Helmert)[H.8]    -1.8668      0.206     -9.079      0.000      -2.271      -1.463
==============================================================================
Omnibus:                       48.011   Durbin-Watson:                   1.255
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               71.510
Skew:                           0.793   Prob(JB):                     2.96e-16
Kurtosis:                       4.341   Cond. No.                         12.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [68]:
res.summary().tables[1]
# Intercept is same as cars_grouped.mean()
# Coefficients are same coeff_cylinder_4, coeff_cylinder_5, coeff_cylinder_6, coeff_cylinder_8

<class 'statsmodels.iolib.table.SimpleTable'>

In [71]:
ce_helmert = ce.HelmertEncoder(cols=['cylinders'])
ce_helmert

HelmertEncoder(cols=['cylinders'])

In [72]:
car_he = ce_helmert.fit_transform(cars)
car_he.head()

intercept   mpg  cylinders_0  cylinders_1  cylinders_2  cylinders_3
0          1  18.0         -1.0         -1.0         -1.0         -1.0
1          1  19.0         -1.0         -1.0         -1.0         -1.0
2          1  23.7         -1.0         -1.0         -1.0         -1.0
3          1  21.5         -1.0         -1.0         -1.0         -1.0
4          1  27.5          1.0         -1.0         -1.0         -1.0

In [73]:
X = car_he.drop(['mpg'], axis=1)
y = car_he['mpg']

In [74]:
lr = LinearRegression(fit_intercept=False)
lr.fit(X, y)
print(f'Score: {lr.score(X, y)}')

Score: 0.6372420899156167


In [81]:
assert np.round(lr.coef_[0], 3) == np.round(cars_grouped['mpg'].mean(), 3)  # Off by signifcant digits
assert np.round(lr.coef_[1], 3) == np.round(coeff_cylinder_4, 3)
assert np.round(lr.coef_[2], 3) == np.round(coeff_cylinder_5, 3)
assert np.round(lr.coef_[3], 3) == np.round(coeff_cylinder_6, 3)
assert np.round(lr.coef_[4], 3) == np.round(coeff_cylinder_8, 3)

In [76]:
lr.coef_

array([22.43045049,  4.36838235,  0.81609477, -1.43719071, -1.86683592])

In [82]:
# Backward Orthogonal Polynomial Contrast Coding
# Looks for linear, quadratic and cubic trends in the categorical variable
# Should only be used for categorical variables with equally spaced levels

cars = pd.read_csv('data/auto-mpg.csv', na_values='?')
cars = cars[['mpg', 'horsepower']].dropna()
cars.reset_index(drop=True, inplace=True)
cars.sample(10)

mpg  horsepower
347  34.4        65.0
4    17.0       140.0
54   27.0        60.0
94   12.0       225.0
343  37.0        65.0
83   27.0        88.0
216  36.0        58.0
253  25.1        88.0
369  36.0        74.0
251  20.5        95.0

In [83]:
cars.corr()

mpg  horsepower
mpg         1.000000   -0.778427
horsepower -0.778427    1.000000

In [84]:
_, bin_edges = np.histogram(cars.horsepower, bins=3)

In [85]:
bin_edges

array([ 46.        , 107.33333333, 168.66666667, 230.        ])

In [86]:
hp_cat = np.digitize(cars.horsepower, bin_edges, True)
hp_cat

array([2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 2, 2, 3, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 2, 1, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 2, 2, 3, 3, 3,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 2, 2, 2,
       3, 2, 2, 3, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 3, 2, 2, 2,
       2, 3, 2, 2, 2, 3, 3, 3, 1, 1, 1, 1, 1, 0, 2, 2, 3, 3, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 3, 1, 1, 1, 2, 2, 2, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       3, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 3, 2, 2, 2, 1, 1, 1, 1, 1, 2,
       2, 2, 2, 2, 1, 1, 1, 3, 3, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,

In [87]:
cars['hp_cat'] = hp_cat
cars.head()

mpg  horsepower  hp_cat
0  18.0       130.0       2
1  15.0       165.0       2
2  18.0       150.0       2
3  16.0       150.0       2
4  17.0       140.0       2

In [88]:
cars = cars[['mpg', 'hp_cat']]

In [89]:
cars_grouped = cars.groupby('hp_cat')
cars_grouped.head()

mpg  hp_cat
0    18.0       2
1    15.0       2
2    18.0       2
3    16.0       2
4    17.0       2
5    15.0       3
6    14.0       3
7    14.0       3
8    14.0       3
9    15.0       3
14   24.0       1
15   22.0       1
16   18.0       1
17   21.0       1
18   27.0       1
19   26.0       0
101  26.0       0

In [90]:
cars_grouped.mean()

mpg
hp_cat           
0       26.000000
1       27.186275
2       17.289320
3       13.296875

In [91]:
cars_grouped.mean().mean()

mpg    20.943117
dtype: float64

In [92]:
mod = smf.ols("mpg ~ C(hp_cat, Poly)", data=cars)
res = mod.fit()
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.453
Model:                            OLS   Adj. R-squared:                  0.448
Method:                 Least Squares   F-statistic:                     106.9
Date:                Sat, 01 Jan 2022   Prob (F-statistic):           1.80e-50
Time:                        12:22:29   Log-Likelihood:                -1243.1
No. Observations:                 392   AIC:                             2494.
Df Residuals:                     388   BIC:                             2510.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
Intercept                    20.9431      1.070     19.577      0.000      18.840      23.046
C(hp_cat, Poly).Linear      -10.7345      2.838     -3.782      0.000     -16.315      -5.154
C(hp_cat, Poly).Quadratic    -2.5894      2.140     -1.210      0.227      -6.796       1.617
C(hp_cat, Poly).Cubic         3.7986      1.048      3.624      0.000       1.738       5.859
==============================================================================
Omnibus:                       15.471   Durbin-Watson:                   0.883
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               16.178
Skew:                           0.480   Prob(JB):                     0.000307
Kurtosis:                       3.266   Cond. No.                         14.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [93]:
from patsy.contrasts import Poly

In [94]:
levels = [0, 1, 2, 3]

In [95]:
contrasts_with_int = Poly().code_with_intercept(levels)
contrasts_with_int

ContrastMatrix(array([[ 1.        , -0.67082039,  0.5       , -0.2236068 ],
                      [ 1.        , -0.2236068 , -0.5       ,  0.67082039],
                      [ 1.        ,  0.2236068 , -0.5       , -0.67082039],
                      [ 1.        ,  0.67082039,  0.5       ,  0.2236068 ]]),
               ['.Constant', '.Linear', '.Quadratic', '.Cubic'])

In [96]:
contrast_without_intercept = Poly().code_without_intercept(levels)
contrast_without_intercept

ContrastMatrix(array([[-0.67082039,  0.5       , -0.2236068 ],
                      [-0.2236068 , -0.5       ,  0.67082039],
                      [ 0.2236068 , -0.5       , -0.67082039],
                      [ 0.67082039,  0.5       ,  0.2236068 ]]),
               ['.Linear', '.Quadratic', '.Cubic'])

In [97]:
cars_contrast = contrast_without_intercept.matrix[cars.hp_cat - 0, :]
cars_contrast[:10]

array([[ 0.2236068 , -0.5       , -0.67082039],
       [ 0.2236068 , -0.5       , -0.67082039],
       [ 0.2236068 , -0.5       , -0.67082039],
       [ 0.2236068 , -0.5       , -0.67082039],
       [ 0.2236068 , -0.5       , -0.67082039],
       [ 0.67082039,  0.5       ,  0.2236068 ],
       [ 0.67082039,  0.5       ,  0.2236068 ],
       [ 0.67082039,  0.5       ,  0.2236068 ],
       [ 0.67082039,  0.5       ,  0.2236068 ],
       [ 0.67082039,  0.5       ,  0.2236068 ]])

In [98]:
cars_contrast_df = pd.DataFrame(cars_contrast, columns=['linear', 'quadratic', 'cubic'])
cars_contrast_df.head()

linear  quadratic    cubic
0  0.223607       -0.5 -0.67082
1  0.223607       -0.5 -0.67082
2  0.223607       -0.5 -0.67082
3  0.223607       -0.5 -0.67082
4  0.223607       -0.5 -0.67082

In [99]:
cars_enc = pd.concat([cars, cars_contrast_df], axis=1)
cars_enc.sample(10)

mpg  hp_cat    linear  quadratic     cubic
193  29.0       1 -0.223607       -0.5  0.670820
255  19.4       1 -0.223607       -0.5  0.670820
71   15.0       2  0.223607       -0.5 -0.670820
122  20.0       2  0.223607       -0.5 -0.670820
89   12.0       3  0.670820        0.5  0.223607
253  25.1       1 -0.223607       -0.5  0.670820
104  13.0       3  0.670820        0.5  0.223607
310  37.2       1 -0.223607       -0.5  0.670820
44   18.0       2  0.223607       -0.5 -0.670820
263  17.5       2  0.223607       -0.5 -0.670820

In [100]:
X = cars_enc.drop(columns=['mpg', 'hp_cat'])
y = cars_enc['mpg']

In [101]:
lr = LinearRegression()
lr.fit(X, y)
print(f'Score: {lr.score(X, y)}')

Score: 0.4526112147657164


In [103]:
lr.coef_, lr.intercept_

(array([-10.73454153,  -2.58935995,   3.79857355]), 20.943117474538354)